export const SET_USER = "SET_USER";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const GET_ARTICLES = "GET_ARTICLES";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT_MEMBER = "ADD_PROJECT_MEMBER";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPLOAD_CERTIFICATES = "UPLOAD_CERTIFICATES";
export const SET_CERTIFICATES = "SET_CERTIFICATES";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const ADD_EVENT = "ADD_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const ERROR = "ERROR";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const UPDATE_EVENT_INTEREST = "UPDATE_EVENT_INTEREST";


